# Generated by Django 4.0.5 on 2022-06-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_classification_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='books.classification'),
            preserve_default=False,
        ),
    ]
